[package]
name           = "tombala"
version        = "1.0.0"
authors        = ["nikos <nikos@mugsoft.io>"]
edition        = "2018"
description    = "Mugsoft Tombala Game"
repository     = "keybase://private/nikosefthias/tombala"
license        = "MIT"
[dependencies]
rand           = "0.6"
serde          = {version="1.0",features=["derive"]}
serde_json     = "1.0"
