[package]
name           = "libtombala"
version        = "2.2.0"
authors        = ["nikos <nikos@mugsoft.io>"]
edition        = "2018"
description    = "Mugsoft Tombala Game"
repository     = "https://github.com/nikosefthias/libtombala"
license        = "MIT"
[dependencies]
rand           = "0.7"
serde          = {version="1.0",features=["derive"]}
serde_json     = "1.0"
