[package]
name           = "tombala"
version        = "0.0.0"
authors        = ["nikos <nikos@mugsoft.io>"]
edition        = "2018"
description    = "Mugsoft Tombala Game"
repository     = "keybase://private/nikosefthias/tombala"
license        = "MIT"
[dependencies]
rand           = "0.6"
clap           = "2.32"
serde          = "1.0"
serde_derive   = "1.0"
serde_json     = "1.0"
[[bin]]
name='server'
path="src/main.rs"
[[bin]]
name="test-client"
path="src/testclient.rs"
